services:

  qwen-vllm:
    build:
      context: .
      dockerfile: Dockerfile.vllm

    image: dgx-qwen36:latest
    container_name: qwen-vllm

    gpus: all
    ipc: host

    ports:
      - "8000:8000"

    environment:
      MODEL_NAME: ${MODEL_NAME}
      SERVED_MODEL_NAME: ${SERVED_MODEL_NAME}

      API_KEY: ${API_KEY}

      MAX_MODEL_LEN: ${MAX_MODEL_LEN}
      GPU_MEMORY_UTILIZATION: ${GPU_MEMORY_UTILIZATION}
      MAX_NUM_SEQS: ${MAX_NUM_SEQS}

    volumes:
      - ./hf-cache:/root/.cache/huggingface

    restart: unless-stopped

  openhands:
    image: docker.openhands.dev/openhands/openhands:1.8
    container_name: openhands

    depends_on:
      - qwen-vllm

    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      APP_BASE_URL: ${APP_BASE_URL}
      AGENT_SERVER_IMAGE_REPOSITORY: ghcr.io/openhands/agent-server
      AGENT_SERVER_IMAGE_TAG: 1.26.0-python

      LOG_ALL_EVENTS: "true"

      SANDBOX_VOLUME_MOUNTS: /workspace:/workspace

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./openhands-state:/.openhands
      - ./workspace:/workspace

    stdin_open: true
    tty: true

    restart: unless-stopped