#!/usr/bin/env python3
"""ntfy_notifier.py — push Agent Canvas status changes to ntfy.

A small daemon that watches the local Agent Canvas agent-server
(conversations' execution_status) and publishes ntfy notifications when a
conversation transitions into a status of interest (finished, idle = waiting
for input, error, stuck, ...).

It is intentionally dependency-free (Python stdlib only) so it can run on
any PC next to Agent Canvas without a venv.

Configuration (environment variables, normally set in agent_canvas_native/.env
by run.sh):

    NTFY_ENABLED=false        # set true to run this daemon
    NTFY_SERVER=http://127.0.0.1:2020   # or https://ntfy.sh for the public server
    NTFY_TOPIC=agent-canvas   # topic to publish to (unguessable!)
    NTFY_AUTH_TOKEN=          # access token for a protected/self-hosted server
    NTFY_TOPIC_MODE=shared    # shared | one-per-PC | one-per-conv
    NTFY_HOSTNAME=            # machine label, default: os hostname
    NTFY_DEEP_LINK_PREFIX=    # e.g. http://mac.tail:8020/conversations/
    NTFY_POLL_SECONDS=5       # poll interval
    NTFY_COOLDOWN_SECONDS=120 # per-(conversation,status) re-notify cooldown
    NTFY_MAX_BODY=4000        # max message body chars (ntfy hard limit is 4096B)
    NTFY_PRIORITIES=idle=3,finished=3,error=5,stuck=4,waiting_for_confirmation=4
    NTFY_EVENTS=              # comma list of statuses to notify on
                              # (default: idle,finished,error,stuck,waiting_for_confirmation)
    NTFY_INCLUDE_MESSAGE=true # include a snippet of the last agent message
    NTFY_BASE_URL=http://127.0.0.1:18000   # agent-server (via ingress or direct)

The agent-server session API key is read (never printed) in this order:
  1. $OH_SESSION_API_KEYS_0 / $LOCAL_BACKEND_API_KEY
  2. ~/.openhands/agent-canvas/api-key.txt (auto-generated by the launcher)

State (last-seen status per conversation, with timestamps for cooldowns)
lives in <state_dir>/ntfy_notifier_state.json next to the Agent Canvas state,
so nothing depends on memory across restarts.

Signal handling: SIGTERM/SIGINT stop the loop cleanly; SIGUSR1 (re)publishes
the current status snapshot for every watched conversation (useful to
re-test the pipeline after changing phone settings).
"""

from __future__ import annotations

import json
import os
import signal
import sys
import time
import urllib.error
import urllib.request
import base64
from datetime import datetime, timezone
from pathlib import Path

VERSION = "1.0.0"

# ntfy hard limit: messages longer than 4096 bytes become attachments.
NTFY_MESSAGE_LIMIT = 4096

# ExecutionStatus values as reported by the agent-server
# (openhands.sdk.conversation.state.ConversationExecutionStatus).
KNOWN_STATUSES = {
    "idle",
    "running",
    "paused",
    "waiting_for_confirmation",
    "finished",
    "error",
    "stuck",
    "deleting",
}

DEFAULT_EVENTS = {
    "idle",
    "finished",
    "error",
    "stuck",
    "waiting_for_confirmation",
}

# status -> (title, priority, tags, deep-link path suffix, emoji prefix)
NOTIFICATION_PRESETS = {
    "finished": (
        "Agent finished",
        3,
        "white_check_mark,robot",
        None,
        "✅",
    ),
    "idle": (
        "Agent finished a turn — needs your input",
        3,
        "eyes,robot",
        None,
        "👀",
    ),
    "waiting_for_confirmation": (
        "Agent is waiting for your confirmation",
        4,
        "warning,robot",
        None,
        "🚦",
    ),
    "error": (
        "Agent hit an error",
        5,
        "rotating_light,robot",
        None,
        "🚨",
    ),
    "stuck": (
        "Agent looks stuck",
        4,
        "warning,snail",
        None,
        "🐌",
    ),
    "paused": (
        "Agent paused",
        2,
        "pause_button",
        None,
        "⏸️",
    ),
    "running": (
        "Agent started running",
        2,
        "rocket",
        None,
        "🚀",
    ),
}


# ---------------------------------------------------------------------------
# small helpers
# ---------------------------------------------------------------------------


def env(key: str, default: str = "") -> str:
    return os.environ.get(key, "").strip() or default


def env_bool(key: str, default: bool = False) -> bool:
    raw = os.environ.get(key, "").strip().lower()
    if not raw:
        return default
    return raw in ("1", "true", "yes", "on")


def log(msg: str) -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    print(f"[ntfy_notifier {ts}] {msg}", flush=True)


def rfc2047_header(value: str) -> str:
    """Encode a header value as RFC 2047 if it can't be sent as latin-1.

    HTTP headers are ISO-8859-1, so arbitrary Unicode (e.g. an em dash or a
    non-ASCII conversation title) must be encoded. ntfy decodes RFC 2047 on
    the Title/Tags headers. Pure-latin-1 values pass through unchanged.
    """
    try:
        value.encode("latin-1")
        return value
    except UnicodeEncodeError:
        b64 = base64.b64encode(value.encode("utf-8")).decode("ascii")
        return f"=?UTF-8?B?{b64}?="


def http_request(
    url: str,
    method: str = "GET",
    headers: dict | None = None,
    body: bytes | None = None,
    timeout: int = 15,
) -> tuple[int, bytes]:
    req = urllib.request.Request(url, data=body, method=method)
    for k, v in (headers or {}).items():
        if v:
            req.add_header(k, v)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status, resp.read()
    except urllib.error.HTTPError as e:
        return e.code, e.read()
    except (urllib.error.URLError, TimeoutError, OSError) as e:
        raise ConnectionError(str(e)) from e


# ---------------------------------------------------------------------------
# agent-server
# ---------------------------------------------------------------------------


class AgentServer:
    def __init__(self, base_url: str, api_key: str):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key

    def _headers(self) -> dict:
        return {"X-Session-API-Key": self.api_key}

    def list_conversations(self, max_items: int = 500) -> list[dict]:
        """List all conversations, paginating (the API caps `limit` at 100)."""
        items: list[dict] = []
        page_id: str | None = None
        while True:
            url = f"{self.base_url}/api/conversations/search?limit=100"
            if page_id:
                url += f"&page_id={page_id}"
            status, body = http_request(url, headers=self._headers())
            if status != 200:
                raise RuntimeError(
                    f"GET conversations failed: HTTP {status} ({body[:200]!r})"
                )
            data = json.loads(body)
            page = data.get("items") or data.get("events") or []
            items.extend(page)
            if len(items) >= max_items or len(page) < 100:
                break
            page_id = data.get("next_page_id") or data.get("page_id")
            if not page_id:
                break
        return items

    def recent_messages(self, conv_id: str, limit: int = 100) -> list[str]:
        """Return recent assistant/user message texts (newest last).

        Tolerant of API shape: reads MessageEvent.llm_message.content which is
        a list of blocks like {"type": "text", "text": "..."} or a string.
        """
        url = f"{self.base_url}/api/conversations/{conv_id}/events/search?limit={limit}"
        try:
            status, body = http_request(url, headers=self._headers())
        except ConnectionError:
            return []
        if status != 200:
            return []
        data = json.loads(body)
        events = data.get("events") or data.get("items") or []
        texts: list[str] = []
        for e in events:
            if e.get("kind") != "MessageEvent":
                continue
            llm = e.get("llm_message") or {}
            content = llm.get("content")
            parts: list[str] = []
            if isinstance(content, str):
                parts.append(content)
            elif isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "text":
                        parts.append(str(block.get("text", "")))
            text = "\n".join(p for p in parts if p).strip()
            if text:
                texts.append(f"{llm.get('role', '?')}: {text}")
        return texts

    def recent_error(self, conv_id: str, limit: int = 50) -> str:
        """Return the most recent AgentErrorEvent error text (or '')."""
        url = f"{self.base_url}/api/conversations/{conv_id}/events/search?limit={limit}"
        try:
            status, body = http_request(url, headers=self._headers())
        except ConnectionError:
            return ""
        if status != 200:
            return ""
        data = json.loads(body)
        events = data.get("events") or data.get("items") or []
        errors: list[str] = []
        for e in events:
            if e.get("kind") != "AgentErrorEvent":
                continue
            err = e.get("error")
            if isinstance(err, str) and err.strip():
                errors.append(err.strip())
            elif isinstance(err, dict):
                errors.append(json.dumps(err, ensure_ascii=False))
        return errors[-1] if errors else ""


# ---------------------------------------------------------------------------
# ntfy publisher
# ---------------------------------------------------------------------------


class NtfyPublisher:
    def __init__(
        self,
        server: str,
        topic: str,
        token: str = "",
        topic_mode: str = "shared",
        hostname: str = "",
        deep_link_prefix: str = "",
        max_body: int = 4000,
        dry_run: bool = False,
    ):
        self.server = server.rstrip("/")
        self.base_topic = topic.strip()
        self.token = token
        self.topic_mode = topic_mode
        self.hostname = hostname
        self.deep_link_prefix = deep_link_prefix.rstrip("/")
        self.max_body = max_body
        self.dry_run = dry_run

    def _auth_headers(self) -> dict:
        if not self.token:
            return {}
        # ntfy accepts Bearer for access tokens.
        return {"Authorization": f"Bearer {self.token}"}

    def _topic_for(self, conv: dict) -> str:
        if self.topic_mode == "one-per-conv":
            return f"{self.base_topic}-{conv['id'][:8]}"
        return self.base_topic

    def _title_for(self, conv: dict, title: str) -> str:
        # one-per-PC mode: every notification is prefixed with the host.
        # shared mode: the topic already separates PCs, but still label so a
        # forwarded/logged message is attributable.
        if self.hostname and self.topic_mode == "one-per-PC":
            return f"{self.hostname}: {title}"
        return title

    def publish(
        self,
        conv: dict,
        status: str,
        snippet: str = "",
        cooldown_key: str | None = None,
    ) -> None:
        preset = NOTIFICATION_PRESETS.get(status)
        if preset is None:
            title, priority, tags, link_suffix, emoji = (
                f"Agent status: {status}",
                2,
                "robot",
                None,
                "•",
            )
        else:
            title, priority, tags, link_suffix, emoji = preset

        conv_title = (conv.get("title") or conv["id"][:12]).strip()
        title = f"{title} — {conv_title}" if conv_title != conv["id"][:12] else title
        title = self._title_for(conv, title)

        click = None
        if self.deep_link_prefix:
            click = f"{self.deep_link_prefix}/{conv['id']}"
            if link_suffix:
                click = f"{click}{link_suffix}"

        body = snippet.strip()
        if len(body) > self.max_body:
            body = body[: self.max_body - 1] + "…"

        headers = {
            "Title": rfc2047_header(title),
            "Priority": str(priority),
            "Tags": rfc2047_header(tags),
            **self._auth_headers(),
        }
        if click:
            headers["Click"] = click

        topic = self._topic_for(conv)
        url = f"{self.server}/{topic}"

        if self.dry_run:
            log(
                f"DRY-RUN publish to {url} :: title={title!r} "
                f"priority={priority} tags={tags} click={click} body={body[:80]!r}"
            )
            return

        status_code, resp = http_request(
            url,
            method="PUT",
            headers=headers,
            body=body.encode("utf-8"),
        )
        if status_code >= 400:
            # Do not dump the body — it may echo back our auth header.
            log(f"WARN: ntfy publish failed HTTP {status_code}")
        else:
            log(
                f"published {status} for conversation {conv['id'][:8]} "
                f"(topic={topic}, priority={priority})"
            )


# ---------------------------------------------------------------------------
# state
# ---------------------------------------------------------------------------


def load_state(path: Path) -> dict:
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict) and isinstance(data.get("conversations"), dict):
            return data
    except (OSError, json.JSONDecodeError):
        pass
    return {"conversations": {}}


def save_state(path: Path, state: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".json.tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)
    os.replace(tmp, path)


# ---------------------------------------------------------------------------
# notifier
# ---------------------------------------------------------------------------


class Notifier:
    def __init__(self, args=None):
        self.base_url = env("NTFY_BASE_URL", "http://127.0.0.1:18000")
        self.poll_seconds = float(env("NTFY_POLL_SECONDS", "5") or 5)
        self.cooldown = float(env("NTFY_COOLDOWN_SECONDS", "120") or 120)
        self.include_message = env_bool("NTFY_INCLUDE_MESSAGE", True)
        self.dry_run = env_bool("NTFY_DRY_RUN", False)
        self.state_path = Path(
            env("NTFY_STATE_FILE", "")
        ) if env("NTFY_STATE_FILE") else None

        # statuses to notify on (whitelist)
        raw_events = env("NTFY_EVENTS", "")
        if raw_events:
            self.events = {s.strip() for s in raw_events.split(",") if s.strip()}
            unknown = self.events - KNOWN_STATUSES
            if unknown:
                log(f"WARNING: unknown status(es) in NTFY_EVENTS: {unknown}")
        else:
            self.events = set(DEFAULT_EVENTS)

        self.publisher = NtfyPublisher(
            server=env("NTFY_SERVER", "http://127.0.0.1:2020"),
            topic=env("NTFY_TOPIC", "agent-canvas"),
            token=env("NTFY_AUTH_TOKEN", ""),
            topic_mode=env("NTFY_TOPIC_MODE", "shared"),
            hostname=self._hostname(),
            deep_link_prefix=env("NTFY_DEEP_LINK_PREFIX", ""),
            max_body=int(env("NTFY_MAX_BODY", str(min(4000, NTFY_MESSAGE_LIMIT)))
                        or 4000),
            dry_run=self.dry_run,
        )

        self._stop = False
        self._api_key: str | None = None
        self.server: AgentServer | None = None

    # -- key resolution -----------------------------------------------------

    @staticmethod
    def _hostname() -> str:
        val = env("NTFY_HOSTNAME", "")
        if val:
            return val
        if hasattr(os, "uname"):
            return os.uname().nodename
        return os.environ.get("HOSTNAME", "agent")

    def resolve_api_key(self) -> str:
        for var in ("OH_SESSION_API_KEYS_0", "LOCAL_BACKEND_API_KEY"):
            val = os.environ.get(var, "").strip()
            if val:
                return val
        key_file = Path.home() / ".openhands" / "agent-canvas" / "api-key.txt"
        if key_file.exists():
            val = key_file.read_text(encoding="utf-8").strip()
            if val:
                return val
        return ""

    def ensure_server(self) -> bool:
        """(Re)create the AgentServer handle once the key is available.

        The launcher writes api-key.txt on first start; if the notifier
        starts slightly earlier, wait for the file to appear.
        """
        if self.server is not None:
            return True
        key = self.resolve_api_key()
        if not key:
            return False
        self._api_key = key
        self.server = AgentServer(self.base_url, key)
        log(f"connected to agent-server at {self.base_url}")
        return True

    # -- notification building ----------------------------------------------

    def build_snippet(self, conv_id: str, status: str) -> str:
        if not self.include_message or self.server is None:
            return ""
        # For errors, surface the actual error text (AgentErrorEvent) rather
        # than the last message — it's the actionable part.
        if status == "error":
            try:
                err = self.server.recent_error(conv_id, limit=100)
            except Exception:
                err = ""
            if err:
                if len(err) > 900:
                    err = "… " + err[-900:]
                return err
        try:
            messages = self.server.recent_messages(conv_id, limit=100)
        except Exception:
            return ""
        # Prefer the most recent assistant message; fall back to any message.
        assistant = [m for m in messages if m.startswith("assistant:")]
        pick = assistant[-1] if assistant else (messages[-1] if messages else "")
        pick = pick.strip()
        if not pick:
            return ""
        if len(pick) > 900:
            pick = "… " + pick[-900:]
        return pick

    def _cooldown_ok(self, state: dict, key: str) -> bool:
        last = state.get("last_notified", {}).get(key, 0)
        return (time.time() - last) >= self.cooldown

    def _record(self, state: dict, key: str) -> None:
        state.setdefault("last_notified", {})[key] = time.time()

    # -- main loop -----------------------------------------------------------

    def poll_once(self, state: dict, force_all: bool = False) -> None:
        if self.server is None:
            return
        try:
            conversations = self.server.list_conversations()
        except (ConnectionError, RuntimeError) as e:
            log(f"WARN: could not list conversations: {e}")
            return

        now = time.time()
        seen: set[str] = set()
        for conv in conversations:
            cid = conv.get("id")
            status = conv.get("execution_status")
            if not cid or not status:
                continue
            seen.add(cid)

            prev = state["conversations"].get(cid, {})
            prev_status = prev.get("status")

            # First sighting: record, but only notify on force_all or if the
            # conversation is already in a terminal/attention status (catch-up
            # after the notifier was restarted).
            first_sight = prev_status is None
            interesting = status in self.events
            should_notify = (
                force_all
                or (
                    interesting
                    and (prev_status != status)
                    and (not first_sight or self.cooldown <= 0)
                )
            )

            # Update tracked status (only on change, to avoid churn).
            if prev_status != status:
                state["conversations"][cid] = {
                    "status": status,
                    "updated_at": now,
                    "title": conv.get("title", ""),
                }

            if should_notify:
                key = f"{cid}:{status}"
                # force_all is a manual re-test (SIGUSR1): bypass the cooldown.
                if force_all or self._cooldown_ok(state, key):
                    snippet = self.build_snippet(cid, status)
                    try:
                        self.publisher.publish(conv, status, snippet)
                        self._record(state, key)
                    except (ConnectionError, OSError) as e:
                        log(f"WARN: publish error: {e}")

        # Drop conversations that disappeared (deleted) to keep state small.
        stale = [c for c in list(state["conversations"]) if c not in seen]
        if stale:
            for c in stale:
                del state["conversations"][c]
            # prune old cooldown keys
            cutoff = now - max(self.cooldown * 10, 3600)
            state.setdefault("last_notified", {})
            for k in [
                k for k, v in state["last_notified"].items() if v < cutoff
            ]:
                del state["last_notified"][k]

    def run(self) -> int:
        log(
            f"ntfy_notifier v{VERSION} starting — "
            f"agent-server={self.base_url} ntfy={self.publisher.server} "
            f"topic={self.publisher.base_topic!r} mode={self.publisher.topic_mode} "
            f"events={sorted(self.events)} dry_run={self.dry_run}"
        )
        if self.state_path is None:
            # Default: <cwd>/openhands-state/ntfy_notifier_state.json. run.sh
            # sets NTFY_STATE_FILE explicitly; this is a safe fallback.
            self.state_path = Path(
                env("NTFY_STATE_FILE", "")
            ) or Path("openhands-state") / "ntfy_notifier_state.json"

        signal.signal(signal.SIGTERM, self._handle_signal)
        signal.signal(signal.SIGINT, self._handle_signal)
        signal.signal(signal.SIGUSR1, self._handle_usr1)

        # Wait for the API key (launcher may still be writing it).
        wait_start = time.time()
        while not self.ensure_server():
            if time.time() - wait_start > 300:
                log("ERROR: no session API key found after 300s; exiting.")
                return 1
            log("waiting for agent-server session API key...")
            time.sleep(2)

        state = load_state(self.state_path)
        log(f"state file: {self.state_path}")

        last_save = 0.0
        while not self._stop:
            t0 = time.time()
            try:
                self.poll_once(state)
            except Exception as e:  # noqa: BLE001 - daemon must keep running
                log(f"ERROR in poll loop: {e}")
            # Persist state at most every 5s and on meaningful changes.
            if t0 - last_save >= 5:
                save_state(self.state_path, state)
                last_save = t0
            # Sleep in small increments so Ctrl+C is responsive.
            deadline = t0 + self.poll_seconds
            while not self._stop and time.time() < deadline:
                time.sleep(0.2)

        save_state(self.state_path, state)
        log("stopped.")
        return 0

    def _handle_signal(self, signum, _frame):
        log(f"received signal {signum}; stopping...")
        self._stop = True

    def _handle_usr1(self, signum, _frame):
        log("SIGUSR1: force-publishing current statuses")
        if self.state_path is not None:
            state = load_state(self.state_path)
            self.poll_once(state, force_all=True)
            save_state(self.state_path, state)


def main() -> int:
    if not env_bool("NTFY_ENABLED", False):
        log("NTFY_ENABLED is not set — nothing to do (this is expected when")
        log("ntfy notifications are disabled).")
        return 0
    notifier = Notifier()
    return notifier.run()


if __name__ == "__main__":
    sys.exit(main())
